"""added file value to item

Revision ID: 39d61a95d441
Revises: 8cf4b8a36068
Create Date: 2021-04-25 14:51:34.176201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d61a95d441'
down_revision = '8cf4b8a36068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
