"""fixed product

Revision ID: 8cf4b8a36068
Revises: da0b011733c4
Create Date: 2021-04-25 14:49:52.648378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf4b8a36068'
down_revision = 'da0b011733c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
